name: CICULLIS

on:
  pull_request:

permissions:
  contents: read

jobs:
  cicullis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run CICULLIS
        uses: midiakiasat/cicullis@v1
        with:
          profile: profiles/default.profile
